# This Playbook contains test scenario for  Create, modify, restart, release RDS instance and change rds instance type, create and delete database , grant account permission and revoke acccount permission
# Playbook created by : 

- name: Testing  Create, modify, restart, release RDS instance and change rds instance type, create and delete database , grant account permission and revoke acccount permission
  hosts: localhost
  connection: local
  vars:
#create rds instance     
    alicloud_region: cn-beijing
    alicloud_zone: 
    db_engine: MySQL 
    engine_version: 5.6
    db_instance_class: rds.mysql.t1.small
    db_instance_storage: 5
    instance_net_type: Intranet
    instance_description: travis-ansible-rds-instance
    security_ip_list: 192.168.0.0
    pay_type: Postpaid
    used_time: 
    connection_mode: Safe  
    instance_network_type: Classic
    private_ip_address:
    allocate_public_ip: true
    public_port: 3306	
    maint_window: 22:00Z-02:00Z
    preferred_backup_time: 22:00Z-23:00Z
    preferred_backup_period: Monday,Tuesday 
    backup_retention_period: 12
    wait: no
    wait_timeout: 20
    db_tags:	
      name: akash
#create database
    db_name: testdemodatabase
    db_description: test
    character_set_name: utf8 
#create account
    account_name: testdemoaccount
    account_password: test@123
    description: 
    account_type: Normal
    account_privilege: ReadOnly

  tasks:
    - name: create rds instance
      rds:
        alicloud_region: '{{ alicloud_region }}'
        alicloud_zone: '{{ alicloud_zone }}'
        command: create
        db_engine: '{{ db_engine }}'
        engine_version: '{{ engine_version }}'
        db_instance_class: '{{ db_instance_class }}'
        db_instance_storage: '{{ db_instance_storage }}'		
        instance_net_type: '{{ instance_net_type }}'
        instance_description: '{{ instance_description }}'
        security_ip_list: '{{ security_ip_list }}'
        pay_type: '{{ pay_type }}'
        used_time: '{{ used_time }}'    
        connection_mode: '{{ connection_mode }}'
        instance_network_type: '{{ instance_network_type }}'        
        private_ip_address:
        allocate_public_ip: '{{ allocate_public_ip }}'
        connection_string_prefix: '{{ ansible_date_time.iso8601_basic }}'
        public_port: '{{ public_port }}'
        maint_window: '{{ maint_window }}'
        preferred_backup_time: '{{ preferred_backup_time }}'
        preferred_backup_period: '{{ preferred_backup_period }}'
        backup_retention_period: '{{ backup_retention_period }}'
        db_tags: '{{ db_tags }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ wait_timeout }}'
      register: result_create_rds_instance
    - debug: var=result_create_rds_instance    

    - name: create account
      rds_account:
        alicloud_region: '{{ alicloud_region }}'
        command: create
        db_instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        account_name: '{{ account_name }}'
        account_password: '{{ account_password }}'
        description: '{{ description }}'
        account_type: '{{ account_type }}'
      register: result_create_account
    - debug: var=result_create_account

    - pause:
        seconds: 30

    - name: Create Database
      rds:
        alicloud_region: '{{ alicloud_region }}'
        command: create
        instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        db_name: '{{ db_name }}'
        db_description: '{{ db_description }}'
        character_set_name: '{{ character_set_name }}'
      register: create_database
    - debug: var=create_database

    - pause:
        seconds: 30

    - name: change rds instance type
      rds:
        alicloud_region: '{{ alicloud_region }}'
        command: modify
        instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        db_instance_class: '{{ db_instance_class }}'
        db_instance_storage: '{{ db_instance_storage }}'
        pay_type: '{{ pay_type }}'
      register: result_changing_rds_instance_type
    - debug: var=result_changing_rds_instance_type

    - pause:
        seconds: 40

    - name: grant account permission
      rds_account:
        alicloud_region: '{{ alicloud_region }}'
        command: grant
        db_instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        db_name: '{{ db_name }}'
        account_name: '{{ account_name }}'
        account_privilege: '{{ account_privilege }}'
      register: result_grant_permission
    - debug: var=result_grant_permission

    - pause:
        seconds: 20    

    - name: revoke account permission
      rds_account:
        alicloud_region: '{{ alicloud_region }}'
        command: revoke
        db_instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        db_name: '{{ db_name }}'
        account_name: '{{ account_name }}'
      register: result_revoke_permission
    - debug: var=result_revoke_permission 

    - pause:
        seconds: 20  
    - name: modify rds instance
      rds:
        alicloud_region: '{{ alicloud_region }}'
        command: modify
        instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        db_instance_class: '{{ db_instance_class }}'
        db_instance_storage: '{{ db_instance_storage }}'		        
        instance_description: '{{ instance_description }}'
        security_ip_list: '{{ security_ip_list }}'
        pay_type: '{{ pay_type }}'      
        maint_window: '{{ maint_window }}'
        preferred_backup_time: '{{ preferred_backup_time }}'
        preferred_backup_period: '{{ preferred_backup_period }}'
        backup_retention_period: '{{ backup_retention_period }}'
      register: result_modify_rds_instance
    - debug: var=result_modify_rds_instance

    - pause:
        seconds: 40

    - name: Reset Instance Password
      rds_account:
        alicloud_region: '{{ alicloud_region }}'
        command: reset_password
        db_instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        account_name: '{{ account_name }}'
        account_password: '{{ account_password }}'     
      register: resetting_instance_password
    - debug: var=resetting_instance_password


    - name: delete account
      rds_account:
        alicloud_region: '{{ alicloud_region }}'
        command: delete
        db_instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        account_name: '{{ account_name }}'
      register: result_delete_account
    - debug: var=result_delete_account

    - pause:
        seconds: 20

    - name: Restart rds instance
      rds:
        alicloud_region: '{{ alicloud_region }}'
        command: reboot
        instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'   
      register: restart_instance
    - debug: var=restart_instance
    
    - pause:
        seconds: 70

    - name: Release rds instance
      rds:
        alicloud_region: '{{ alicloud_region }}'
        command: delete
        instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'   
      register: release_instance
    - debug: var=release_instance